/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RoutesJDialog.java
 *
 * Created on 08-mar-2010, 22:06:10
 */

package com.gg.dailymoney.gui;

/**
 *
 * @author Chiquitica
 */
public class RoutesJDialog extends javax.swing.JDialog {

    /** Creates new form RoutesJDialog */
    public RoutesJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelToolbar = new javax.swing.JPanel();
        jButtonPrev = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jButtonFind = new javax.swing.JButton();
        jButtonNewRoute = new javax.swing.JButton();
        jButtonRemoveRoute = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonNotebook = new javax.swing.JButton();
        jButtonHelp = new javax.swing.JButton();
        jPanelContent = new javax.swing.JPanel();
        jPanelBottom = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(":: Rutas ::");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelToolbar.setLayout(new java.awt.GridBagLayout());

        jButtonPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gg/dailymoney/res/icons/32x32/previous.png"))); // NOI18N
        jButtonPrev.setToolTipText("Mostrar la ruta anterior");
        jButtonPrev.setMargin(new java.awt.Insets(4, 7, 4, 7));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelToolbar.add(jButtonPrev, gridBagConstraints);

        jButtonNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gg/dailymoney/res/icons/32x32/next.png"))); // NOI18N
        jButtonNext.setToolTipText("Mostrar la ruta siguiente");
        jButtonNext.setMargin(new java.awt.Insets(4, 7, 4, 7));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelToolbar.add(jButtonNext, gridBagConstraints);

        jButtonFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gg/dailymoney/res/icons/32x32/filefind.png"))); // NOI18N
        jButtonFind.setToolTipText("Buscar una ruta");
        jButtonFind.setMargin(new java.awt.Insets(4, 7, 4, 7));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelToolbar.add(jButtonFind, gridBagConstraints);

        jButtonNewRoute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gg/dailymoney/res/icons/32x32/filenew.png"))); // NOI18N
        jButtonNewRoute.setToolTipText("Crear una ruta nueva");
        jButtonNewRoute.setMargin(new java.awt.Insets(4, 7, 4, 7));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelToolbar.add(jButtonNewRoute, gridBagConstraints);

        jButtonRemoveRoute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gg/dailymoney/res/icons/32x32/editdelete.png"))); // NOI18N
        jButtonRemoveRoute.setToolTipText("Borrar esta ruta");
        jButtonRemoveRoute.setMargin(new java.awt.Insets(4, 7, 4, 7));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelToolbar.add(jButtonRemoveRoute, gridBagConstraints);

        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gg/dailymoney/res/icons/32x32/filesave.png"))); // NOI18N
        jButtonSave.setToolTipText("Guuardar los cambios");
        jButtonSave.setMargin(new java.awt.Insets(4, 7, 4, 7));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelToolbar.add(jButtonSave, gridBagConstraints);

        jButtonNotebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gg/dailymoney/res/icons/32x32/contents.png"))); // NOI18N
        jButtonNotebook.setToolTipText("Ver la libreta de esta ruta");
        jButtonNotebook.setMargin(new java.awt.Insets(4, 7, 4, 7));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelToolbar.add(jButtonNotebook, gridBagConstraints);

        jButtonHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gg/dailymoney/res/icons/32x32/help.png"))); // NOI18N
        jButtonHelp.setToolTipText("Ayuda");
        jButtonHelp.setMargin(new java.awt.Insets(4, 7, 4, 7));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelToolbar.add(jButtonHelp, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(jPanelToolbar, gridBagConstraints);

        jPanelContent.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(jPanelContent, gridBagConstraints);

        jPanelBottom.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(jPanelBottom, gridBagConstraints);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-800)/2, (screenSize.height-600)/2, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RoutesJDialog dialog = new RoutesJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFind;
    private javax.swing.JButton jButtonHelp;
    private javax.swing.JButton jButtonNewRoute;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonNotebook;
    private javax.swing.JButton jButtonPrev;
    private javax.swing.JButton jButtonRemoveRoute;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JPanel jPanelBottom;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelToolbar;
    // End of variables declaration//GEN-END:variables

}
