/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RoutesJDialog.java
 *
 * Created on 08-mar-2010, 22:06:10
 */

package com.gg.dailymoney.gui;

/**
 *
 * @author Chiquitica
 */
public class RoutesJDialog extends javax.swing.JDialog {

    /** Creates new form RoutesJDialog */
    public RoutesJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelToolbar = new javax.swing.JPanel();
        jButtonPrev = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jButtonFind = new javax.swing.JButton();
        jButtonNewRoute = new javax.swing.JButton();
        jButtonRemoveRoute = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonNotebook = new javax.swing.JButton();
        jButtonHelp = new javax.swing.JButton();
        jPanelContent = new javax.swing.JPanel();
        jPanelRoute = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldRouteName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelCollector = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCollectorName = new javax.swing.JTextField();
        jPanelBottom = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(":: Rutas ::");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelToolbar.setLayout(new java.awt.GridBagLayout());

        jButtonPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gg/dailymoney/res/icons/32x32/previous.png"))); // NOI18N
        jButtonPrev.setToolTipText("Mostrar la ruta anterior");
        jButtonPrev.setMargin(new java.awt.Insets(4, 7, 4, 7));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelToolbar.add(jButtonPrev, gridBagConstraints);

        jButtonNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gg/dailymoney/res/icons/32x32/next.png"))); // NOI18N
        jButtonNext.setToolTipText("Mostrar la ruta siguiente");
        jButtonNext.setMargin(new java.awt.Insets(4, 7, 4, 7));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelToolbar.add(jButtonNext, gridBagConstraints);

        jButtonFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gg/dailymoney/res/icons/32x32/filefind.png"))); // NOI18N
        jButtonFind.setToolTipText("Buscar una ruta");
        jButtonFind.setMargin(new java.awt.Insets(4, 7, 4, 7));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelToolbar.add(jButtonFind, gridBagConstraints);

        jButtonNewRoute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gg/dailymoney/res/icons/32x32/filenew.png"))); // NOI18N
        jButtonNewRoute.setToolTipText("Crear una ruta nueva");
        jButtonNewRoute.setMargin(new java.awt.Insets(4, 7, 4, 7));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelToolbar.add(jButtonNewRoute, gridBagConstraints);

        jButtonRemoveRoute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gg/dailymoney/res/icons/32x32/editdelete.png"))); // NOI18N
        jButtonRemoveRoute.setToolTipText("Borrar esta ruta");
        jButtonRemoveRoute.setMargin(new java.awt.Insets(4, 7, 4, 7));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelToolbar.add(jButtonRemoveRoute, gridBagConstraints);

        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gg/dailymoney/res/icons/32x32/filesave.png"))); // NOI18N
        jButtonSave.setToolTipText("Guuardar los cambios");
        jButtonSave.setMargin(new java.awt.Insets(4, 7, 4, 7));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelToolbar.add(jButtonSave, gridBagConstraints);

        jButtonNotebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gg/dailymoney/res/icons/32x32/contents.png"))); // NOI18N
        jButtonNotebook.setToolTipText("Ver la libreta de esta ruta");
        jButtonNotebook.setMargin(new java.awt.Insets(4, 7, 4, 7));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelToolbar.add(jButtonNotebook, gridBagConstraints);

        jButtonHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gg/dailymoney/res/icons/32x32/help.png"))); // NOI18N
        jButtonHelp.setToolTipText("Ayuda");
        jButtonHelp.setMargin(new java.awt.Insets(4, 7, 4, 7));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelToolbar.add(jButtonHelp, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 2, 2);
        getContentPane().add(jPanelToolbar, gridBagConstraints);

        jPanelContent.setLayout(new java.awt.GridBagLayout());

        jPanelRoute.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelRoute.add(jLabel1, gridBagConstraints);

        jTextFieldRouteName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldRouteName.setMinimumSize(new java.awt.Dimension(350, 20));
        jTextFieldRouteName.setPreferredSize(new java.awt.Dimension(350, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelRoute.add(jTextFieldRouteName, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanelContent.add(jPanelRoute, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Clientes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelContent.add(jLabel3, gridBagConstraints);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanelContent.add(jScrollPane1, gridBagConstraints);

        jPanelCollector.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Cobrador");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelCollector.add(jLabel2, gridBagConstraints);

        jTextFieldCollectorName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldCollectorName.setMinimumSize(new java.awt.Dimension(350, 20));
        jTextFieldCollectorName.setPreferredSize(new java.awt.Dimension(350, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelCollector.add(jTextFieldCollectorName, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanelContent.add(jPanelCollector, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 2, 2);
        getContentPane().add(jPanelContent, gridBagConstraints);

        jPanelBottom.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos financieros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanelBottom.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Capital invertido");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 2);
        jPanelBottom.add(jLabel4, gridBagConstraints);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("0");
        jTextField1.setMinimumSize(new java.awt.Dimension(100, 21));
        jTextField1.setPreferredSize(new java.awt.Dimension(100, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 2, 5, 10);
        jPanelBottom.add(jTextField1, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Capital recogido");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 2);
        jPanelBottom.add(jLabel5, gridBagConstraints);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setText("0");
        jTextField2.setMinimumSize(new java.awt.Dimension(100, 21));
        jTextField2.setPreferredSize(new java.awt.Dimension(100, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 2, 5, 10);
        jPanelBottom.add(jTextField2, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Intereses obtenidos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 2);
        jPanelBottom.add(jLabel6, gridBagConstraints);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.setText("0");
        jTextField3.setMinimumSize(new java.awt.Dimension(100, 21));
        jTextField3.setPreferredSize(new java.awt.Dimension(100, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 2, 5, 5);
        jPanelBottom.add(jTextField3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 2, 2);
        getContentPane().add(jPanelBottom, gridBagConstraints);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-800)/2, (screenSize.height-600)/2, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RoutesJDialog dialog = new RoutesJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFind;
    private javax.swing.JButton jButtonHelp;
    private javax.swing.JButton jButtonNewRoute;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonNotebook;
    private javax.swing.JButton jButtonPrev;
    private javax.swing.JButton jButtonRemoveRoute;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanelBottom;
    private javax.swing.JPanel jPanelCollector;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelRoute;
    private javax.swing.JPanel jPanelToolbar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldCollectorName;
    private javax.swing.JTextField jTextFieldRouteName;
    // End of variables declaration//GEN-END:variables

}
